echo ""
echo "The following commands are available:"
echo ""
echo "0. ./info.sh - Prints all possible commands"
echo "1. ./mac-setup.sh - Configures MacOS"
echo "2. ./homebrew-setup.sh - Installs homebrew packages and casks (GUI applications)"
echo "3. ./bash-setup.sh - Adds homebrew bash (as opposed to system bash) to the list of viable shells"
echo "4. ./zsh-setup.sh - Configures zsh terminal"
echo "5. ./appstore-setup.sh - Installs appstore applications"
echo "6. ./git-setup.sh - Configures Git global username and email"
echo "7. ./asdf-setup.sh - Installs all programming languages"
echo "8. ./rustup-setup.sh - Installs rust tooling"
echo "9. ./vscode-setup.sh - Configures vscode for development"
echo "10. ./ssh-setup.sh - Sets up ssh configuration"
echo "11. ./github-setup.sh - Clone all public repos from a github user"
echo ""
